---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf2gAwIBAgIQLzZtB2Hlofc+HPMygNbtmTAKBggqhkjOPQQDAjB2MQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
          Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yMjEwMTcwNjQ1MDBaFw0zMjEwMTQwNjQ1
          MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
          Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
          VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
          AQcDQgAEFyscOi0k2MQJKius9i4PFI677/qEkjZ4NooHQ1t7cz8oEcdScx5I6n7z
          R6eT4p26KDDPeN/vjIuL4KUqdDyQg6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
          JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
          DgQiBCBxwbh/yewveYogPYvnL0q/VkQeHcipQ3WYHWitPuFFWzAKBggqhkjOPQQD
          AgNIADBFAiEA+cK6fk/yewl88aldKVnsDV5Ic0McZQ4Jq++zVSMq77ECIFAr1TYU
          2sI4MUPaq1cNGXadspePXCGuHmptDGlHLTg4
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUjCCAfegAwIBAgIQJ6ZF36Tp9rIjL29pm8RAtjAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMS5leGFtcGxlLmNvbTAeFw0yMjEwMTcwNjQ1MDBaFw0zMjEwMTQwNjQ1MDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          nSuLseDcK8RGbdnnnNBPUK74Mifyz9qW61FcLyKdWXOQY7ejuEZTbDJov9t10dtf
          V9CQdpa+IFIyQKSOKvLFdqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCF
          Z0vJp3a6tEG0Wo21B9UmrcEYi/cPMuyNnIRkObDOWjAKBggqhkjOPQQDAgNJADBG
          AiEAkZYuS5x4XXZXACz3hU198iHId64q+blQqTsnb7QAsxYCIQCo54Ytb+erYt2U
          edjF4EzU+F1Pb2ShuwHWXf92QPpfWg==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
